---
functional:
  - Не зарегистрированный пользователь может запустить пробную игру
  - Пользователь может зарегистрироваться по электронной почте
  - Пользователь может авторизоваться через электронную почту
  - Пользователь может авторизоваться через Github
  - Пользователь может авторизоваться через Discord
  - Пользователь может ознакоиться с FAQ  
  - Пользователь может создать игру
  - Пользователь может создать игру с другим пользователем
  - Пользователь может создать игру с другим пользователем из списка друзей 
  - Пользователь может создать игру с ботом
  - Пользователь может выбрать уровень сложности при создании игры
  - Пользователь может выбрать время раунда в игре
  - Пользователь может выбрать задачу по названию или тегам
  - Пользователь может подключиться к созданной игре другого пользователя
  - Пользователь может выбрать язык программирования для решение задач (Clojure, C++, C#, Dart, Elixir, Haskell, Go, Java, Node.JS, Kotlin, Php, Phyton, Ruby, Rust, Typescript)
  - Пользователь может ознакомиться с заданием, при старте игры
  - Пользователь может выбрать язык, на котором написано задание (RU, EN)
  - Пользователь может писать, вставлять, удалять данные в редакторе кода
  - Пользователь может видеть результаты тестов исполнения кода (TaskOutput)
  - Пользователь может видететь редактор кода соперника в реальном времени
  - Пользователь может ознакомиться с заданием, при старте игры
  
non-functional:
  - Сайт должен обрабатывать не менее 1000 одновременных пользователей без значительного ухудшения скорости загрузки страниц
  - Сайт должен быть доступен 99.9% времени в месяц, включая время на техническое обслуживание
  - Сайт должен быть масштабируемым. Система должна быть способна увеличивать ресурсы для поддержки роста числа пользователей и увеличения нагрузки без необходимости полной переработки архитектуры
  - Сайт должен защищать данные пользователей, включая личную информацию и результаты соревнований, с помощью современных методов шифрования и аутентификации
  - Сайт должен быть удобным в использовании. Интерфейс должен быть интуитивно понятным для пользователей с разным уровнем подготовки в программировании, с простой навигацией и доступом к необходимой информации
  - На сайте должна быть кросс-браузерная совместимость. Сайт должен корректно отображаться и функционировать во всех популярных браузерах (Chrome, Firefox, Safari, Edge) и на мобильных устройствах
  - Сайт должен быть локализован. Платформа должна поддерживать несколько языков, чтобы обеспечить доступность для пользователей из разных стран
  - Сайт должен быть отказоустойчивым. Система должна продолжать функционировать в случае сбоя одного из компонентов, обеспечивая резервное копирование данных и возможность быстрого восстановления
  - Сайт должен быть с мониторингом и логированием. Сайт должен иметь механизм мониторинга производительности и логирования ошибок для быстрого выявления и решения проблем
  - Сайт должно быть обновляемость. Архитектура сайта должна быть спроектирована так, чтобы упрощать внедрение новых функций и исправлений без значительных простоев


implicit:
  - Дизайн сайта должен быть современным и привлекательным, создавая положительное первое впечатление у пользователей
  - Качество кода. Код, написанный участниками, должен оцениваться по стандартам чистоты и читаемости, что может не быть явно прописанным в правилах
  - Сообщество и взаимодействие. Ожидается наличие механизма для общения пользователей, например, через комментарии или форумы, что способствует обмену опытом
  - Гибкость в правилах. Участники могут ожидать, что правила соревнований будут адаптироваться в зависимости от текущих трендов в программировании
  - Поддержка и обучение. Пользователи должны иметь доступ к учебным материалам и ресурсам для повышения своих навыков, что способствует их вовлеченности
  - Чувствительность к обратной связи. Команда разработчиков будет реагировать на отзывы пользователей и вносить улучшения на основе их предложений
  - Поддержка различных языков программирования. Участники могут ожидать, что сайт будет поддерживать актуальные и популярные языки программирования, а не только несколько базовых
  - Пользователи могут ожидать, что за участие и победу в соревнованиях будут предусмотрены привлекательные призы или награды
  
